#   ▗▄▄▖▗▄▄▄▖▗▄▖ ▗▄▄▖▗▄▄▄▖▗▖ ▗▖▗▄▄▖ 
#  ▐▌     █ ▐▌ ▐▌▐▌ ▐▌ █  ▐▌ ▐▌▐▌ ▐▌
#   ▝▀▚▖  █ ▐▛▀▜▌▐▛▀▚▖ █  ▐▌ ▐▌▐▛▀▘ 
#  ▗▄▄▞▘  █ ▐▌ ▐▌▐▌ ▐▌ █  ▝▚▄▞▘▐▌

# ---------------- Startup Variables ----------------

$scriptsDir = $HOME/.config/scripts
$themes = $HOME/.config/hypr/themes
$lock = $scriptsDir/LockScreen.sh
$WallpaperPath = $HOME/Pictures/wallpapers


# ---------------- System Environment ----------------
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP


# ---------------- System Services ----------------
exec-once = systemctl --user start hyprpolkitagent

# ---------------- Startup Applications ----------------
exec-once = pkill kde6
exec-once = hyprpaper
exec-once = waypaper --restore
exec-once = $scriptsDir/StartWaybar.sh
exec-once = swaync &
exec-once = nm-applet --indicator &
exec-once = opensnitch-ui &
exec-once = wl-paste --watch cliphist store
exec-once = hypridle -q
exec-once = gsettings set org.gnome.desktop.interface cursor-theme "Bibata-Modern-Ice"
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps

exec-once = blueman-applet
exec-once = tailscale up

# This script creates two virtual audio outputs (GameOutput and ChatOutput) 
# then set arctis 7 as default output and chat output as default input
exec = ! $scriptsDir/IsLaptop.sh && $scriptsDir/SetUpAudio.sh

#This script starts a python script that controls mixer volume for arctis 7
exec = ! $scriptsDir/IsLaptop.sh && $scriptsDir/ArctisStartup.sh